export const categories = [
    { value: "all", label: "All" },
    { value: "technology", label: "Technology" },
    { value: "travel", label: "Travel" },
    { value: "healthandfitness", label: "Health and Fitness" },
    { value: "foodandcooking", label: "Food and Cooking" },
    { value: "fashionandstyle", label: "Fashion and Style" },
    { value: "personalfinance", label: "Personal Finance" },
    { value: "investment", label: "Investment" },
    { value: "trading", label: "Trading" },
    { value: "lifestyle", label: "Lifestyle" },
    { value: "parenting", label: "Parenting" },
    { value: "entertainment", label: "Entertainment" },
    { value: "sportsandrecreation", label: "Sports and Recreation" },
    { value: "education", label: "Education" },
    { value: "businessandentrepreneurship", label: "Business and Entrepreneurship" },
    { value: "homeanddecor", label: "Home and Decor" },
    { value: "selfimprovement", label: "Self-Improvement" },
    { value: "artsandculture", label: "Arts and Culture" },
    { value: "scienceandnature", label: "Science and Nature" },
    { value: "newsandcurrentevents", label: "News and Current Events" },
    { value: "gaming", label: "Gaming" },
    { value: "photography", label: "Photography" },
    { value: "music", label: "Music" },
];
